version: '2'
services:
  opsgenie-alerts-manager:
    image: shalb/opsgenie-alerts-manager:0.0.1
    volumes:
      - ./exporter:/opt/exporter
    restart: always
    ports:
      - "127.0.0.1:9647:9647"
    environment:
      - OPSGENIE_API_KEY=00000000-0000-0000-0000-000000000000
      - 'OPSGENIE_QUERY=status: open AND source: JiraServiceManagement'
      - OPSGENIE_QUERY_LIMIT=100
      - SCHEDULER_TIME=17:00
     #- LOG_LEVEL=INFO|DEBUG
     #- MAIN_LOOP_SLEEP_INTERVAL=10
     #- LISTEN_PORT=9647
   #entrypoint: ["/bin/bash", "-c", "sleep 9999"]
